version: 2
builds:
  - id: cli
    binary: gdqcli
    main: ./cmd/gdqcli
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: cli
    builds:
      - cli
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
