// Code generated by eventgen; DO NOT EDIT.

package gdq

// All the GDQ events, sorted by Event.ID
var (
	SGDQ2012         = Event{ID: 1, Short: "SGDQ2012", Name: "Summer Games Done Quick", Year: 2012}
	AGDQ2012         = Event{ID: 2, Short: "AGDQ2012", Name: "Awesome Games Done Quick", Year: 2012}
	SGDQ2011         = Event{ID: 3, Short: "SGDQ2011", Name: "Summer Games Done Quick", Year: 2011}
	JRDQ             = Event{ID: 4, Short: "JRDQ", Name: "Japan Relief Done Quick", Year: 2011}
	AGDQ2011         = Event{ID: 5, Short: "AGDQ2011", Name: "Awesome Games Done Quick", Year: 2011}
	CGDQ             = Event{ID: 6, Short: "CGDQ", Name: "Classic Games Done Quick", Year: 2010}
	AGDQ2013         = Event{ID: 7, Short: "AGDQ2013", Name: "Awesome Games Done Quick", Year: 2013}
	SGDQ2013         = Event{ID: 8, Short: "SGDQ2013", Name: "Summer Games Done Quick", Year: 2013}
	AGDQ2014         = Event{ID: 9, Short: "AGDQ2014", Name: "Awesome Games Done Quick", Year: 2014}
	SGDQ2014         = Event{ID: 10, Short: "SGDQ2014", Name: "Summer Games Done Quick", Year: 2014}
	AGDQ2015         = Event{ID: 12, Short: "AGDQ2015", Name: "Awesome Games Done Quick", Year: 2015}
	Spook            = Event{ID: 13, Short: "Spook", Name: "Speedrun Spooktacular", Year: 2012}
	SGDQ2015         = Event{ID: 16, Short: "SGDQ2015", Name: "Summer Games Done Quick", Year: 2015}
	AGDQ2016         = Event{ID: 17, Short: "AGDQ2016", Name: "Awesome Games Done Quick", Year: 2016}
	SGDQ2016         = Event{ID: 18, Short: "SGDQ2016", Name: "Summer Games Done Quick", Year: 2016}
	AGDQ2017         = Event{ID: 19, Short: "AGDQ2017", Name: "Awesome Games Done Quick", Year: 2017}
	SGDQ2017         = Event{ID: 20, Short: "SGDQ2017", Name: "Summer Games Done Quick", Year: 2017}
	HRDQ             = Event{ID: 21, Short: "HRDQ", Name: "Harvey Relief Done Quick", Year: 2017}
	AGDQ2018         = Event{ID: 22, Short: "AGDQ2018", Name: "Awesome Games Done Quick", Year: 2018}
	SGDQ2018         = Event{ID: 23, Short: "SGDQ2018", Name: "Summer Games Done Quick", Year: 2018}
	GDQX2018         = Event{ID: 24, Short: "GDQX2018", Name: "Games Done Quick Express", Year: 2018}
	AGDQ2019         = Event{ID: 25, Short: "AGDQ2019", Name: "Awesome Games Done Quick", Year: 2019}
	SGDQ2019         = Event{ID: 26, Short: "SGDQ2019", Name: "Summer Games Done Quick", Year: 2019}
	GDQX2019         = Event{ID: 27, Short: "GDQX2019", Name: "Games Done Quick Express", Year: 2019}
	AGDQ2020         = Event{ID: 28, Short: "AGDQ2020", Name: "Awesome Games Done Quick", Year: 2020}
	FrostFatales2020 = Event{ID: 29, Short: "FrostFatales2020", Name: "Frost Fatales", Year: 2020}
	SGDQ2020         = Event{ID: 30, Short: "SGDQ2020", Name: "Summer Games Done Quick", Year: 2020}
	CRDQ             = Event{ID: 31, Short: "CRDQ", Name: "Corona Relief Done Quick", Year: 2020}
	THPSLaunch       = Event{ID: 32, Short: "THPSLaunch", Name: "Tony Hawk's Pro Skater 1 + 2 Launch Celebration", Year: 2020}
	FleetFatales2020 = Event{ID: 33, Short: "FleetFatales2020", Name: "Fleet Fatales", Year: 2020}
	AGDQ2021         = Event{ID: 34, Short: "AGDQ2021", Name: "Awesome Games Done Quick 2021 Online", Year: 2021}
	SGDQ2021         = Event{ID: 35, Short: "SGDQ2021", Name: "Summer Games Done Quick 2021 Online", Year: 2021}
	FlameFatales2021 = Event{ID: 36, Short: "FlameFatales2021", Name: "Flame Fatales", Year: 2021}
	AGDQ2022         = Event{ID: 37, Short: "AGDQ2022", Name: "Awesome Games Done Quick 2022 Online", Year: 2022}
	FrostFatales2022 = Event{ID: 38, Short: "FrostFatales2022", Name: "Frost Fatales", Year: 2022}
	SGDQ2022         = Event{ID: 39, Short: "SGDQ2022", Name: "Summer Games Done Quick", Year: 2022}
	FlameFatales2022 = Event{ID: 40, Short: "FlameFatales2022", Name: "Flame Fatales", Year: 2022}
	AGDQ2023         = Event{ID: 41, Short: "AGDQ2023", Name: "Awesome Games Done Quick", Year: 2023}
	FrostFatales2023 = Event{ID: 42, Short: "FrostFatales2023", Name: "Frost Fatales", Year: 2023}
	SGDQ2023         = Event{ID: 43, Short: "SGDQ2023", Name: "Summer Games Done Quick", Year: 2023}
	FlameFatales2023 = Event{ID: 44, Short: "FlameFatales2023", Name: "Flame Fatales", Year: 2023}
	GDQX2023         = Event{ID: 45, Short: "GDQX2023", Name: "Games Done Quick Express", Year: 2023}
	AGDQ2024         = Event{ID: 46, Short: "AGDQ2024", Name: "Awesome Games Done Quick", Year: 2024}
	FrostFatales2024 = Event{ID: 47, Short: "FrostFatales2024", Name: "Frost Fatales", Year: 2024}
	SGDQ2024         = Event{ID: 48, Short: "SGDQ2024", Name: "Summer Games Done Quick", Year: 2024}
	FlameFatales2024 = Event{ID: 49, Short: "FlameFatales2024", Name: "Flame Fatales", Year: 2024}
	SSAtPAXWest      = Event{ID: 50, Short: "SSAtPAXWest", Name: "Speedrun Stage @ PAX West", Year: 2024}
	GDQX2024         = Event{ID: 51, Short: "GDQX2024", Name: "Games Done Quick Express", Year: 2024}
	AGDQ2025         = Event{ID: 52, Short: "AGDQ2025", Name: "Awesome Games Done Quick", Year: 2025}
	DRDQ2024         = Event{ID: 53, Short: "DRDQ2024", Name: "Disaster Relief Done Quick", Year: 2024}
	BTB2025          = Event{ID: 54, Short: "BTB2025", Name: "Back to Black", Year: 2025}
)

var eventsByName = map[string]Event{
	"sgdq2012":         SGDQ2012,
	"agdq2012":         AGDQ2012,
	"sgdq2011":         SGDQ2011,
	"jrdq":             JRDQ,
	"agdq2011":         AGDQ2011,
	"cgdq":             CGDQ,
	"agdq2013":         AGDQ2013,
	"sgdq2013":         SGDQ2013,
	"agdq2014":         AGDQ2014,
	"sgdq2014":         SGDQ2014,
	"agdq2015":         AGDQ2015,
	"spook":            Spook,
	"sgdq2015":         SGDQ2015,
	"agdq2016":         AGDQ2016,
	"sgdq2016":         SGDQ2016,
	"agdq2017":         AGDQ2017,
	"sgdq2017":         SGDQ2017,
	"hrdq":             HRDQ,
	"agdq2018":         AGDQ2018,
	"sgdq2018":         SGDQ2018,
	"gdqx2018":         GDQX2018,
	"agdq2019":         AGDQ2019,
	"sgdq2019":         SGDQ2019,
	"gdqx2019":         GDQX2019,
	"agdq2020":         AGDQ2020,
	"frostfatales2020": FrostFatales2020,
	"sgdq2020":         SGDQ2020,
	"crdq":             CRDQ,
	"thpslaunch":       THPSLaunch,
	"fleetfatales2020": FleetFatales2020,
	"agdq2021":         AGDQ2021,
	"sgdq2021":         SGDQ2021,
	"flamefatales2021": FlameFatales2021,
	"agdq2022":         AGDQ2022,
	"frostfatales2022": FrostFatales2022,
	"sgdq2022":         SGDQ2022,
	"flamefatales2022": FlameFatales2022,
	"agdq2023":         AGDQ2023,
	"frostfatales2023": FrostFatales2023,
	"sgdq2023":         SGDQ2023,
	"flamefatales2023": FlameFatales2023,
	"gdqx2023":         GDQX2023,
	"agdq2024":         AGDQ2024,
	"frostfatales2024": FrostFatales2024,
	"sgdq2024":         SGDQ2024,
	"flamefatales2024": FlameFatales2024,
	"ssatpaxwest":      SSAtPAXWest,
	"gdqx2024":         GDQX2024,
	"agdq2025":         AGDQ2025,
	"drdq2024":         DRDQ2024,
	"btb2025":          BTB2025,
}

var eventsByID = map[uint]Event{
	1:  SGDQ2012,
	2:  AGDQ2012,
	3:  SGDQ2011,
	4:  JRDQ,
	5:  AGDQ2011,
	6:  CGDQ,
	7:  AGDQ2013,
	8:  SGDQ2013,
	9:  AGDQ2014,
	10: SGDQ2014,
	12: AGDQ2015,
	13: Spook,
	16: SGDQ2015,
	17: AGDQ2016,
	18: SGDQ2016,
	19: AGDQ2017,
	20: SGDQ2017,
	21: HRDQ,
	22: AGDQ2018,
	23: SGDQ2018,
	24: GDQX2018,
	25: AGDQ2019,
	26: SGDQ2019,
	27: GDQX2019,
	28: AGDQ2020,
	29: FrostFatales2020,
	30: SGDQ2020,
	31: CRDQ,
	32: THPSLaunch,
	33: FleetFatales2020,
	34: AGDQ2021,
	35: SGDQ2021,
	36: FlameFatales2021,
	37: AGDQ2022,
	38: FrostFatales2022,
	39: SGDQ2022,
	40: FlameFatales2022,
	41: AGDQ2023,
	42: FrostFatales2023,
	43: SGDQ2023,
	44: FlameFatales2023,
	45: GDQX2023,
	46: AGDQ2024,
	47: FrostFatales2024,
	48: SGDQ2024,
	49: FlameFatales2024,
	50: SSAtPAXWest,
	51: GDQX2024,
	52: AGDQ2025,
	53: DRDQ2024,
	54: BTB2025,
}
