name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
        contents: write
    name: Build and package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Check formatting
      run: test -z $(gofmt -l **.go)
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
