name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
        contents: write
    name: Build and package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Check formatting
      run: test -z $(gofmt -l **.go)
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
